title: rayvn
description: A bash shared library framework
theme: just-the-docs
color_scheme: dark
url: https://rayvn.ink
baseurl: /rayvn

nav_external_links:
  - title: GitHub
    url: https://github.com/phoggy/rayvn

sass:
  quiet_deps: true
  silence_deprecations: [import]

aux_links:
  "rayvn.ink": "/"
